
-- Wyłączam RLS na wszystkich tabelach - nie potrzebujemy JWT
ALTER TABLE public.wizyty DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pacjenci DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.notatki_dzienne DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.urlopy DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.plany_pracy DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sms_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.administrators DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cron_logs DISABLE ROW LEVEL SECURITY;
;
